apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 207717182806.dkr.ecr.ap-southeast-2.amazonaws.com/cloud-backend:latest
          ports:
            - containerPort: 5000 # หรือ port ที่ backend ของคุณใช้