apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: 207717182806.dkr.ecr.ap-southeast-1.amazonaws.com/cloud-backend:v2

        env:
        - name: DATABASE_URL
          value: mysql://admin:awd486S5@database-1.cliu62ai6o1e.ap-southeast-1.rds.amazonaws.com:3306/mysql

        ports:
        - containerPort: 3000

        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "500m"